In [2]:
import torch
import os
from glob import glob
from tqdm import tqdm

In [383]:
hf = glob("/newcpfs/user/liuyanjiang/Eng/agi-verl/recipe/moe/moe_trainer/dump_dir_2/*")
verl = glob("/newcpfs/user/liuyanjiang/Eng/agi-verl/recipe/moe/moe_trainer/dump_dir/*")

In [384]:
hf_layer0 = [i for i in hf if "layers.1" in i and "mbs1" in i]
verl_layer0 = [i for i in verl if "layers.1" in i]

In [385]:
hf_layer0_input = [i for i in hf_layer0 if "input" in i]
verl_layer0_input = [i for i in verl_layer0 if "input" in i]

In [386]:
[i for i in verl_layer0_input if "insp" in i]

['/newcpfs/user/liuyanjiang/Eng/agi-verl/recipe/moe/moe_trainer/dump_dir/model.layers.1.mlp.gate.inspect2-iter-mbs0-forward-input.pt',
 '/newcpfs/user/liuyanjiang/Eng/agi-verl/recipe/moe/moe_trainer/dump_dir/model.layers.1.mlp.inspect_param-iter-mbs0-forward-input.pt',
 '/newcpfs/user/liuyanjiang/Eng/agi-verl/recipe/moe/moe_trainer/dump_dir/model.layers.1.mlp.inspect_param2-iter-mbs0-forward-input.pt',
 '/newcpfs/user/liuyanjiang/Eng/agi-verl/recipe/moe/moe_trainer/dump_dir/model.layers.1.mlp.gate.inspect-iter-mbs0-forward-input.pt']

In [448]:
hf_a = torch.load(
    "/newcpfs/user/liuyanjiang/Eng/agi-verl/recipe/moe/moe_trainer/dump_dir_2/model.layers.2.mlp.gate-iter-mbs0-forward-output.pt",
    map_location="cpu",
    weights_only=False,
)
verl_a = torch.load(
    "/newcpfs/user/liuyanjiang/Eng/agi-verl/recipe/moe/moe_trainer/dump_dir/model.layers.2.mlp.gate-iter-mbs0-forward-output.pt",
    map_location="cpu",
    weights_only=False,
)

In [449]:
torch.allclose(hf_a[0], verl_a[0], rtol=1e-5, atol=1e-8)

True

In [450]:
verl_a

(tensor([[ 12,  24,  51,  71,  83,  86],
         [ 14,  23,  24,  37, 114,  74],
         [  3,  23,  37, 107, 123,  29],
         ...,
         [ 17,  36,  38,  94,  45,  49],
         [ 17,  36,  38,  94,  45,  49],
         [ 17,  36,  38,  94,  45,  49]]),
 tensor([[0.4184, 0.3977, 0.4881, 0.3874, 0.4390, 0.3693],
         [0.4302, 0.4012, 0.4651, 0.4041, 0.4012, 0.3983],
         [0.4146, 0.4146, 0.4114, 0.4335, 0.4146, 0.4114],
         ...,
         [0.4186, 0.4153, 0.4169, 0.4186, 0.4169, 0.4137],
         [0.4186, 0.4153, 0.4169, 0.4186, 0.4169, 0.4137],
         [0.4186, 0.4153, 0.4169, 0.4186, 0.4169, 0.4137]], requires_grad=True),
 None)

In [451]:
hf_a

(tensor([[ 12,  24,  51,  71,  83,  86],
         [ 14,  23,  24,  37, 114,  74],
         [  3,  23,  37, 107, 123,  29],
         ...,
         [ 17,  36,  38,  94,  45,  49],
         [ 17,  36,  38,  94,  45,  49],
         [ 17,  36,  38,  94,  45,  49]]),
 tensor([[0.4184, 0.3977, 0.4881, 0.3874, 0.4390, 0.3693],
         [0.4302, 0.4012, 0.4651, 0.4041, 0.4012, 0.3983],
         [0.4146, 0.4146, 0.4114, 0.4335, 0.4146, 0.4114],
         ...,
         [0.4186, 0.4153, 0.4169, 0.4186, 0.4169, 0.4137],
         [0.4186, 0.4153, 0.4169, 0.4186, 0.4169, 0.4137],
         [0.4186, 0.4153, 0.4169, 0.4186, 0.4169, 0.4137]], requires_grad=True),
 None)

In [178]:
verl_a[0][1024:]

tensor([[ 17,  46,  51,  68,  82,  14],
        [ 12,  48,  86,  98, 105,  90],
        [  4,  90, 112, 121,   5,   8],
        ...,
        [  9,  17,  51,  75,   7,  14],
        [  9,  17,  51,  75,   7,  14],
        [  9,  17,  51,  75,   7,  14]])